export enum PERMISSION{
  MANAGE_ORGANIZATION='MANAGE_ORGANIZATION',
  MANAGE_ORGANIZATION_ADMINS='MANAGE_ORGANIZATION_ADMINS',
  EDIT_ORGANIZATION_DETAILS='EDIT_ORGANIZATION_DETAILS',
  ADD_DELETE_TEACHER='ADD_DELETE_TEACHER',
  ADD_DELETE_TEACHER_ASSISTANT='ADD_DELETE_TEACHER_ASSISTANT',
  DELETE_STUDENT_ACCOUNT='DELETE_STUDENT_ACCOUNT',
  ACCEPT_STUDENT_ACCESS_REQUEST='ACCEPT_STUDENT_ACCESS_REQUEST',
  CREATE_FLASHCARD_SET='CREATE_FLASHCARD_SET',
  DELETE_FLASHCARD_SET='DELETE_FLASHCARD_SET',
  CREATE_FLASHCARD='CREATE_FLASHCARD',
  DELETE_FLASHCARD='DELETE_FLASHCARD',
  START_STOP_GAME='START_STOP_GAME'
}
